name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Write Fullkey.snk
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/src/fullkey.snk
        encodedString: ${{ secrets.SIGNKEY }}

    - name: Create msbuild params
      run: |
        echo "::set-output name=params::${{ github.event.repository.name }}.csproj -verbosity:minimal /p:Configuration=Release /property:DisableGitVersionTask=true /property:GitVersion_NuGetVersion=${{ github.event.release.tag_name }}"
      id: msbuild
    
    - name: add nuget API Key for releases
      if: "!github.event.release.prerelease"
      run: |
        echo "::set-output name=params::/property:NugetAPIKey=${{ secrets.NugetAPIKey }}"      
      id: apikey

    - name: Restore
      working-directory: src
      run: |
        dotnet restore --disable-parallel

    - name: Restore & Build & (Publish)
      working-directory: src
      run: |
        msbuild ${{ steps.msbuild.outputs.params }} ${{ steps.apikey.outputs.params }}
        rm -R .\obj\Release
        msbuild ${{ steps.msbuild.outputs.params }} ${{ steps.apikey.outputs.params }} /property:UnSigned=true

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: src/bin/Release/*.nupkg
